name: Laravel

on:
  push:
    branches:
      - main
      - 'releases/*'
  pull_request:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Change this if you are using a different version
          extensions: mbstring, xml, bcmath
          coverage: none

      - name: Install Composer
        run: composer install --prefer-dist --no-progress --no-suggest --no-ansi --no-interaction

      - name: Run Tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Check Code Style
        run: vendor/bin/phpcs --standard=PSR12 src/

      - name: Analyze Code with PHPStan
        run: vendor/bin/phpstan analyse
